[[plugins]]
package = "netlify-plugin-a11y"
  [plugins.inputs]
  checkPaths = [
    '/blog/',
    '/about-me/',
    '/blog/lang-attribute/',
  ]
[[plugins]]
package = "netlify-plugin-cache-folder"

[build]  
  command = "CI= npm run build"

[[redirects]]
  from = "/htmltest"
  to = "https://cdpn.io/pen/debug/zYqQeRw"

[[redirects]]
  from = "/blog/2022/twitter-ban2/"
  to = "/blog/2022/your-account-is-permanently-suspended/"

[[redirects]]
  from = "/blog/2022/100daysof-day71/"
  to = "/blog/2023/100daysof-day71/"