[[plugins]]
package = "netlify-plugin-a11y"
  [plugins.inputs]
  checkPaths = [
    '/blog/',
    '/about-me/',
    '/blog/lang-attribute/',
  ]
[[plugins]]
package = "netlify-plugin-cache-folder"

[build]  
  command = "npm run build"
