backend:
  name: git-gateway

publish_mode: editorial_workflow

media_folder: 'static/img/uploads'

collections:
  - name: 'talks' # Used in routes, e.g., /admin/collections/blog
    label: 'Talks' # Used in the UI
    folder: 'talks' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{day}}-{{month}}-{{hour}}-{{minute}}-{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Talk title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Link to slides', name: 'slides', widget: 'string', required: false }
      - { label: 'Link to video', name: 'video', widget: 'string', required: false }
  - name: 'events' # Used in routes, e.g., /admin/collections/blog
    label: 'Events' # Used in the UI
    folder: 'events' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Name of the event', name: 'title', widget: 'string' }
      - { label: 'Url', name: 'url', widget: 'string' }
      - { label: 'Logo', name: 'logo', widget: 'image' }
  - name: 'speaking' # Used in routes, e.g., /admin/collections/blog
    label: 'Speaking' # Used in the UI
    folder: 'speaking' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'date' }
      - { label: 'Event', name: 'event', widget: 'relation',  collection: "events",  searchFields: ["title"], valueField: "title" }
      - { label: 'Talk', name: 'talk', widget: 'relation',  collection: "talks",  searchFields: ["title"], valueField: "title" }
      - label: 'City'
        name: 'country'
        widget: 'select'
        options:
          - { label: "Berlin", value: "DE" }
          - { label: "Budapest", value: "HU" }
          - { label: "Cologne", value: "DE" }
          - { label: "Erlangen", value: "DE" }
          - { label: "Graz", value: "AT" }
          - { label: "Linz", value: "AT" }
          - { label: "Minsk", value: "BY" }
          - { label: "Moscow", value: "RU" }
          - { label: "Salzburg", value: "AT" }
          - { label: "St. Petersburg", value: "RU" }
          - { label: "Toronto", value: "CA" }
          - { label: "Vienna", value: "AT" }
          - { label: "Warsaw", value: "PL" }
