backend:
  name: git-gateway

publish_mode: editorial_workflow

media_folder: 'static/img/uploads'

collections:
  - name: 'speaking' # Used in routes, e.g., /admin/collections/blog
    label: 'Speaking' # Used in the UI
    folder: 'speaking' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Talk title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Summary', name: 'summary', widget: 'text' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Link to slides', name: 'slides', widget: 'string' }
      - { label: 'Link to video', name: 'video', widget: 'string' }
